export const enum ENotificationType {

  FLIGHT_UPDATED = 'FLIGHT_UPDATED',

  FLIGHT_CANCELLED = 'FLIGHT_CANCELLED',

  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',

  BOOKING_CANCELLED = 'BOOKING_CANCELLED'

}
